name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure App Service Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: acacia-main
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C5D939DE3A934165A318B4D1179039A5 }}
          package: ./build


          